### ISSUE TITLE
Contributing New Website Themes

### ISSUE THREAD

**Issue by actualaardvark** [Moonlight-theme/Moonlight#1]
Recently I have been working to add Moonlight theme support to a handful of websites using the Stylus extension. If I wanted to contribute those themes to this repository, how would I do so?

**Comment by Abod1960** [comment]
Initially it is better to join our community [here](https://discord.gg/E6kbQnfHNy), and we can discuss this even further so u could contribute to this project...
much appreciation for having interest in the theme
